# Generated by Django 4.0.5 on 2022-06-27 22:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='fence',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='streammessage',
            name='message',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='', srid=4326),
        ),
        migrations.AlterField(
            model_name='streammessage',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
